### ISSUE TITLE
Apply Custom Rules YML voids all rules

### ISSUE THREAD

**Issue by kingargyle** [detekt/detekt-intellij-plugin#387]
With the latest plugin in Android Studio Dolphin, if I try to add a configuration file yml, and apply it.   It appears that the rules are not applied and not even the default rules.    This can be replicated simply enough by taking the default configuration file from:

https://raw.githubusercontent.com/detekt/detekt/main/detekt-core/src/main/resources/default-detekt-config.yml

And adding it as a Configuration file.   Apply it, and then go to a file that you know has rules violations.  No detekt rules are shown.

If you remove the file, and just go with the default from the plugin, then those rules are available and are applied as expected.

Add the custom rules back in and no detekt rules are shown.

**Comment by rdoupe** [comment]
I just did the same thing, and I'm seeing the same results with Intellij Ultimate  2022.2.3

**Comment by rdoupe** [comment]
I was able to get this working by using "Build rules upon default configuration"
<img width="542" alt="image" src="https://user-images.githubusercontent.com/1207041/202270943-c3d8009c-a601-4986-b7f8-534ef03a61af.png">

and the following `detekt.yml` which overrides `maxIssues` and `MaxLineLength`
```
build:
  maxIssues: 99999

style:
  MaxLineLength:
    active: true
    maxLineLength: 140
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
    excludeRawStrings: true

```

this will work for me, but it's not ideal that it doesn't work with the default plugin.

I also had to restart Intellij for the plugin to detekt the changes.
