### ISSUE TITLE
inconsistent error reporting by plugin and detekt

### ISSUE THREAD

**Issue by os97673** [detekt/detekt-intellij-plugin#504]
I have
```
potential-bugs:
  active: true
  severity: error
  ImplicitDefaultLocale:
    active: true
```
in my detekt.yml and when I run detekt it reports problem in the code as error
![image](https://github.com/detekt/detekt-intellij-plugin/assets/450628/de7a7e9a-416b-4a21-b740-9a56c6007bfc)
but in the editor (Android Studio Hedgehog | 2023.1.1 Patch 1) the problem is shown as a warning :-(
<img width="797" alt="Screenshot 2024-01-04 at 7 44 15 AM" src="https://github.com/detekt/detekt-intellij-plugin/assets/450628/36ec32f3-6a60-426f-b1f8-03d4a7c795de">

The detekt plugin (2.3.0) is configured to use the config, but it looks like it overrides severity with "treat detekt findings as errors" (which is not checked by my because I don't want ALL findings from the config to be reported as error)
Is this expected behavior or is this a bug?
