### ISSUE TITLE
Difference in how exclude paths are evaluated after upgrade to 1.0.0-RC1 

### ISSUE THREAD

**Issue by Whathecode** [detekt/detekt-intellij-plugin#63]
I upgraded to the 1.0.0-RC1 plugin, and all of a sudden IntelliJ shows errors for test function names. I did not receive these before, and I do not receive them by running gradle detekt either.

The source file in question should be excluded for this rule (`FunctionNaming`) based on `excludes: "**/commonTest/**,**/jvmTest/**,**/jsTest/**,**/test/**"` in the yml file.

**Comment by arturbosch** [comment]
I've found the problem and tested the fix with a basic config:

```yml
formatting:
  NoConsecutiveBlankLines:
    active: true
    excludes: '**/DetektAnnotator.kt'
```

@Whathecode please verify if the fix works for you, thanks!
